# -*- coding: utf-8 -*-
"""Week_6_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16zo3TeOyAQaGAbs3cDHQQwxjrFdMIfbp
"""

# Assignment
## A Dataset with advanced statistical techniques to a dataset, presenting findings and insights

import pandas as pd
import numpy as np

# Muslim student names
students = ['Fatima', 'Muhammad', 'Aisha', 'Ali', 'Khadija']

# Create synthetic student marks data
np.random.seed(0)
subjects = ['Math', 'Science', 'English', 'History']
marks_data = {
    'Student': np.random.choice(students, size=100),
    'Subject': np.random.choice(subjects, size=100),
    'Marks': np.random.randint(50, 100, size=100)
}

# Create a DataFrame
marks_df = pd.DataFrame(marks_data)

# Display the first few rows of the dataset
print("Student Marks Data:")
print(marks_df.head())
print()

# Summary statistics
print("Summary Statistics:")
print(marks_df.groupby('Subject')['Marks'].describe())
print()

# Correlation analysis
subject_pivot = marks_df.pivot_table(index='Student', columns='Subject', values='Marks')
print("Correlation Analysis:")
print(subject_pivot.corr())
print()

# Subject-wise performance
print("Subject-wise Performance:")
subject_performance = marks_df.groupby('Subject')['Marks'].mean().sort_values(ascending=False)
print(subject_performance)
print()

# Student-wise performance
print("Student-wise Performance:")
student_performance = marks_df.groupby('Student')['Marks'].mean().sort_values(ascending=False)
print(student_performance)
print()

# Visualization: Subject-wise performance
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
plt.bar(subject_performance.index, subject_performance.values, color='skyblue')
plt.xlabel('Subject')
plt.ylabel('Average Marks')
plt.title('Subject-wise Performance')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()